/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import javax.swing.JFrame;
import model.ReceiverModel;
import model.UserModel;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author admin
 */
public class HomeView extends javax.swing.JFrame {

    /**
     * Creates new form HomeView
     */
    private UserModel model;
    
//        public HomeView(UserModel model){
//        this.model=model;
//    }
        
    public HomeView(UserModel model ) {
        this.model=model;
        initComponents();
   // Center the frame on the screen
        setLocationRelativeTo(null);
        
        // Set the frame to not be resizable
        setResizable(false);
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        donateLbl = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        doonateRqstLbl = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        donateSearchLbl = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        logOutLbl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(244, 172, 183));
        jPanel1.setForeground(new java.awt.Color(204, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 202, 212));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(196, 212, 202));

        donateLbl.setText("Donate");
        donateLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                donateLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                donateLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                donateLblMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(donateLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(donateLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 280, 50));

        jPanel5.setBackground(new java.awt.Color(184, 204, 191));

        doonateRqstLbl.setText("Request Donation");
        doonateRqstLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doonateRqstLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                doonateRqstLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                doonateRqstLblMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(doonateRqstLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(doonateRqstLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 280, 50));

        jPanel6.setBackground(new java.awt.Color(172, 195, 180));

        donateSearchLbl.setText("Search Donations");
        donateSearchLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                donateSearchLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                donateSearchLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                donateSearchLblMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(donateSearchLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(donateSearchLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 280, 50));

        jPanel7.setBackground(new java.awt.Color(160, 186, 169));

        logOutLbl.setText("Log Out");
        logOutLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOutLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOutLblMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logOutLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logOutLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 280, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 470));

        jPanel3.setBackground(new java.awt.Color(244, 172, 183));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 460, 460));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void donateLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donateLblMouseClicked
        // TODO add your handling code here:
        System.out.println("Donate Label Clicked");
        TableView tableView = new TableView(model);
        tableView.setVisible(true);
        tableView.pack();
        tableView.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_donateLblMouseClicked

    private void donateLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donateLblMouseEntered
        // TODO add your handling code here:
        donateLbl.setForeground(Color.BLUE);
    }//GEN-LAST:event_donateLblMouseEntered

    private void donateLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donateLblMouseExited
        // TODO add your handling code here:
        donateLbl.setForeground(Color.BLACK);
    }//GEN-LAST:event_donateLblMouseExited

    private void doonateRqstLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doonateRqstLblMouseClicked
        // TODO add your handling code here:
        System.out.println("Request Label Clickked");
        ReceiverModel benefeciary = new ReceiverModel();
        RequestsView reqView = new RequestsView(model,benefeciary);
        
        reqView.setVisible(true);
        reqView.pack();
        reqView.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_doonateRqstLblMouseClicked

    private void doonateRqstLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doonateRqstLblMouseEntered
        // TODO add your handling code here:
        doonateRqstLbl.setForeground(Color.BLUE);
    }//GEN-LAST:event_doonateRqstLblMouseEntered

    private void doonateRqstLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doonateRqstLblMouseExited
        // TODO add your handling code here:
        doonateRqstLbl.setForeground(Color.BLACK);
    }//GEN-LAST:event_doonateRqstLblMouseExited

    private void donateSearchLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donateSearchLblMouseClicked
        // TODO add your handling code here:
        System.out.println("Search Donation Clicked");
    }//GEN-LAST:event_donateSearchLblMouseClicked

    private void donateSearchLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donateSearchLblMouseEntered
        // TODO add your handling code here:
        donateSearchLbl.setForeground(Color.BLUE);
    }//GEN-LAST:event_donateSearchLblMouseEntered

    private void donateSearchLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donateSearchLblMouseExited
        // TODO add your handling code here:
        donateSearchLbl.setForeground(Color.BLACK);
    }//GEN-LAST:event_donateSearchLblMouseExited

    private void logOutLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutLblMouseClicked
        // TODO add your handling code here:
        System.out.println("Log out Label Clicked");
    }//GEN-LAST:event_logOutLblMouseClicked

    private void logOutLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutLblMouseEntered
        // TODO add your handling code here:
        logOutLbl.setForeground(Color.BLUE);
    }//GEN-LAST:event_logOutLblMouseEntered

    private void logOutLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutLblMouseExited
        // TODO add your handling code here:
        logOutLbl.setForeground(Color.BLACK);
    }//GEN-LAST:event_logOutLblMouseExited

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeView(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel donateLbl;
    private javax.swing.JLabel donateSearchLbl;
    private javax.swing.JLabel doonateRqstLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel logOutLbl;
    // End of variables declaration//GEN-END:variables
}
